apiVersion: v1
kind: Service
metadata:
  name: hello-minikube2
  namespace: default
  labels:
    app: hello-minikube2
spec:
  selector:
    app: hello-minikube2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 30090
  type: NodePort